ossf-package-analysis:
    confident/: confident/20250821/073043-npm-@bitkub-next-frontend-v2/app-bitkub-next-1.13.0.json
reversing-labs:
    RLMA-: RLMA-2025-04089.json
    RLUA-: RLUA-2025-04083.json
