ossf-package-analysis:
    confident/: confident/20250806/173944-npm-productboard-eslint-plugin-relay-10123.0.1112.json
reversing-labs:
    RLMA-: RLMA-2025-04089.json
    RLUA-: RLUA-2025-04083.json
