ossf-package-analysis:
    confident/: confident/20250913/202338-npm-@callcenter-frontend/services-99.0.2025091-3.12.json
reversing-labs:
    RLMA-: RLMA-2025-04727.json
    RLUA-: RLUA-2025-04684.json
