ossf-package-analysis:
    confident/: confident/20250909/114636-npm-arm-package-deploymentscripts-2019-10-preview-8.0.1.json
reversing-labs:
    RLMA-: RLMA-2025-04727.json
    RLUA-: RLUA-2025-04684.json
